export const articles: Record<string, { title: string; excerpt: string; category: string; date: string; readTime: string; tags: string[]; content: string }> = {
  "how-high-pressure-misting-works": {
    title: "Cómo Funciona la Nebulización de Alta Presión: La Ciencia del Enfriamiento Evaporativo",
    excerpt: "Comprenda la física detrás de la atomización de gotas a nivel de micrones.",
    category: "technical", date: "2026-05-15", readTime: "8 min", tags: ["tecnología", "ciencia del enfriamiento"],
    content: "## La Física del Enfriamiento Evaporativo\n\nCuando el agua pasa de líquido a vapor, absorbe 2.257 kilojulios de energía térmica por litro — este es el calor latente de vaporización, y es el principio fundamental detrás de todos los sistemas de nebulización.\n\n### Por Qué Importa la Presión\n\nLos rociadores de jardín estándar operan a 2-5 bares y producen gotas de 100-500 micrones de diámetro. Estas gotas grandes tienen una baja relación superficie-volumen, lo que significa que se evaporan lentamente — si es que lo hacen. ¿El resultado? Superficies mojadas y enfriamiento marginal.\n\nLos sistemas de nebulización de alta presión operan a 70-150 bares, forzando el agua a través de orificios cerámicos de precisión de tan solo 0,15 mm. Esto crea gotas de 5-15 micrones de diámetro — más pequeñas que un cabello humano (70 micrones).\n\n### La Ventaja de la Superficie\n\nUn solo litro de agua atomizado en gotas de 10 micrones crea aproximadamente 1,9 billones de gotas individuales con un área superficial combinada de aproximadamente 600 m\u00B2. Esta enorme superficie permite una evaporación casi instantánea.\n\n### Evaporación Instantánea en Acción\n\nCuando estas microgotas salen de la boquilla a alta velocidad, encuentran el aire ambiente y comienzan a evaporarse inmediatamente. El cambio de fase de líquido a vapor absorbe calor directamente del aire circundante. Las gotas se evaporan completamente dentro de 0,5-1,5 metros de la boquilla — mucho antes de que puedan entrar en contacto con personas o superficies.\n\n### Resultados Medibles\n\nEn pruebas controladas, nuestros sistemas logran:\n- Reducción de temperatura de 5-8\u00B0C a 2 metros de las boquillas\n- Reducción de 8-15\u00B0C en temperatura percibida (considerando el efecto del viento)\n- Aumento de humedad relativa del 15-25% (beneficioso en climas secos)\n- Cero humectación superficial más allá de 1,5 metros\n\n### El Desafío de Ingeniería\n\nLograr una atomización consistente a nivel de micrones requiere:\n- Boquillas cerámicas de precisión con orificios perforados por láser\n- Suministro de presión estable (bombas controladas por VFD)\n- Filtración de agua multietapa para prevenir obstrucciones\n- Espaciado adecuado de boquillas y altura de montaje óptima para cobertura de niebla"
  },
  "high-pressure-vs-low-pressure-misting": {
    title: "Nebulización de Alta Presión vs Baja Presión: Una Comparación Técnica",
    excerpt: "La presión importa. Una comparación técnica detallada.",
    category: "technical", date: "2026-05-10", readTime: "6 min", tags: ["tecnología", "comparación"],
    content: "## El Espectro de Presión\n\nLos sistemas de nebulización operan en un amplio rango de presión, desde unidades domésticas de 7 bares hasta sistemas industriales de 150 bares. Comprender estas diferencias es crítico para compradores B2B.\n\n### Sistemas de Baja Presión (7-20 bares)\n- Tamaño de gota: 50-100 micrones\n- Evaporación: Parcial. Las superficies se mojan.\n- Eficiencia de enfriamiento: Reducción de 2-4\u00B0C\n- Ideal para: Pequeños patios residenciales (solo climas secos)\n- Costo: $200-$800\n\n### Sistemas de Presión Media (20-50 bares)\n- Tamaño de gota: 30-50 micrones\n- Evaporación: Moderada. Cierta humectación superficial.\n- Eficiencia de enfriamiento: Reducción de 3-6\u00B0C\n- Ideal para: Pequeños patios comerciales\n- Costo: $800-$3.000\n\n### Sistemas de Alta Presión (70-150 bares)\n- Tamaño de gota: 5-15 micrones\n- Evaporación: Evaporación instantánea completa\n- Eficiencia de enfriamiento: Reducción de 8-15\u00B0C\n- Ideal para: Comercial, industrial, resorts\n- Costo: $8.000-$55.000\n\n### Por Qué 100Cooling Solo Construye de Alta Presión\n\nLa física es inequívoca: solo los sistemas de alta presión logran una evaporación completa. Para aplicaciones comerciales donde la comodidad del huésped y cero humectación son innegociables, cualquier valor inferior a 70 bares es inadecuado. Nuestros sistemas de 150 bares representan el límite superior de presión alcanzable para la atomización de agua."
  },
  "outdoor-cooling-for-restaurants-guide": {
    title: "Soluciones de Enfriamiento Exterior para Restaurantes: Una Guía Completa",
    excerpt: "Cómo los restaurantes aumentan los ingresos de mesas exteriores con nebulización.",
    category: "application", date: "2026-04-28", readTime: "10 min", tags: ["restaurantes", "hostelería", "ROI"],
    content: "## La Oportunidad de Comedor Exterior para Restaurantes\n\nLas mesas exteriores generan tickets promedio un 20-40% más altos que las mesas interiores. Los comensales permanecen más tiempo, piden más bebidas y regresan con más frecuencia cuando los espacios exteriores son confortables.\n\n### El Problema\n\nEn climas tropicales y subtropicales, el comedor exterior se vuelve impracticable durante 4-8 meses al año. Los restaurantes pierden el 30-50% de su capacidad de asientos durante las horas pico de la tarde — precisamente cuando el comedor exterior es más deseable.\n\n### La Solución 100Cooling\n\nLíneas de nebulización montadas en techo o integradas en pérgolas crean una envolvente de enfriamiento invisible sobre las áreas de comedor. Consideraciones clave de instalación:\n\n**Ubicación de Boquillas:** Montadas a 2,5-3,5 metros de altura, espaciadas 0,8-1,2 metros a lo largo del perímetro.\n\n**Control por Zonas:** Divida el espacio en zonas controladas independientemente (área de bar, comedor principal, secciones privadas).\n\n**Control de Mosquitos Vespertino:** El mismo sistema suministra nebulización repelente programada durante las horas pico de mosquitos (5PM-9PM).\n\n### Datos Reales de ROI\n\nNuestros clientes de restaurantes reportan:\n- Aumento del 30-60% en ingresos de mesas exteriores\n- Extensión de la temporada de comedor exterior en 3-6 meses\n- Aumento del 22% en el tiempo promedio de permanencia\n- ROI alcanzado en 6-12 meses\n\n### Caso de Ejemplo\n\nUn restaurante frente al mar de 120 asientos en Phuket instaló 100Cooling en toda su terraza. Antes: terraza cerrada junio-septiembre, abierta pero subutilizada octubre-mayo. Después: terraza completamente operativa todo el año, ingresos aumentaron un 40%, se convirtió en la sección más reservada del restaurante."
  },
  "factory-floor-cooling-productivity": {
    title: "Enfriamiento de Pisos de Fábrica: Reduciendo el Estrés Térmico y Mejorando la Productividad",
    excerpt: "Cómo la nebulización industrial ofrece ganancias de productividad medibles.",
    category: "application", date: "2026-04-20", readTime: "7 min", tags: ["industrial", "productividad", "ROI"],
    content: "## El Costo Oculto del Calor en la Manufactura\n\nLos pisos de fábrica en regiones tropicales superan rutinariamente los 35-40\u00B0C. La investigación muestra:\n- La productividad del trabajador cae un 2% por cada grado por encima de 26\u00B0C\n- Las tasas de accidentes aumentan un 6% por cada grado por encima de 30\u00B0C\n- El ausentismo aumenta un 15-25% durante las olas de calor\n\n### Por Qué el Enfriamiento Tradicional Falla\n\nAcondicionar con aire una fábrica de 15.000 m\u00B2 con techos de 12 metros es económicamente imposible. Los costos de energía superarían los $50.000/mes. El enfriamiento puntual con ventiladores no proporciona ninguna reducción de temperatura.\n\n### El Enfoque Industrial de 100Cooling\n\nLíneas de nebulización dirigidas sobre las estaciones de trabajo crean zonas de microclima. Los trabajadores experimentan 26-28\u00B0C mientras la temperatura ambiente de la fábrica permanece a 35\u00B0C+. Costo de energía: aproximadamente $200/mes para una instalación de 5.000 m\u00B2.\n\n### Resultados Medibles\n\nTechTronics Manufacturing, Shenzhen (15.000 m\u00B2):\n- Temperatura del piso: 38\u00B0C → 26\u00B0C (medida en estaciones de trabajo)\n- Productividad: +22%\n- Tasa de defectos: -18%\n- Ausentismo: -31%\n- ROI: 8 meses\n\n### Beneficio Adicional de Supresión de Polvo\n\nLa nebulización industrial también suprime las partículas de polvo en el aire. En instalaciones de procesamiento de madera, textiles y minería, esto proporciona beneficios adicionales de cumplimiento normativo y salud laboral."
  },
  "how-to-choose-misting-system": {
    title: "Cómo Elegir el Sistema de Enfriamiento Exterior Adecuado",
    excerpt: "Una lista de verificación integral para el comprador para evaluar propuestas.",
    category: "buyers-guide", date: "2026-04-12", readTime: "9 min", tags: ["guía del comprador", "evaluación"],
    content: "## La Lista de Verificación de 10 Puntos para Evaluar Sistemas de Nebulización\n\n### 1. Presión de Operación\nPregunte por la clasificación real de presión de la bomba, no por afirmaciones de marketing. Los sistemas industriales deben especificar 70-150 bares. Desconfíe de sistemas que afirmen \"alta presión\" por debajo de 50 bares.\n\n### 2. Especificaciones de Boquillas\nSolicite el tamaño del orificio (debe ser 0,15 mm o menor), material (cerámico > acero inoxidable) y mecanismo antigoteo.\n\n### 3. Construcción de la Bomba\nCabezal de bomba en acero inoxidable 316L es el estándar de la industria. Componentes de latón o aluminio indican equipos de grado doméstico.\n\n### 4. Etapas de Filtración\nUn mínimo de 3 etapas de filtración es esencial. Se recomiendan 5 etapas para uso comercial. 10 etapas para industrial o agua dura.\n\n### 5. Sistema de Control\nBusque control a nivel de zona, programación basada en clima, capacidad de monitoreo remoto y registro de datos.\n\n### 6. Material de Tubería\nAcero inoxidable 316L para instalaciones permanentes. Nylon aceptable para aplicaciones temporales/de alquiler.\n\n### 7. Términos de Garantía\nEstándar de la industria: 3-5 años en bomba, 2-3 años en boquillas. Garantías extendidas indican confianza del fabricante.\n\n### 8. Certificaciones\nVerifique ISO 9001, marcado CE, cumplimiento RoHS. Certificación UL requerida para mercados norteamericanos.\n\n### 9. Soporte de Instalación\n¿Proporciona el fabricante supervisión de instalación? ¿Hay socios certificados en su región?\n\n### 10. Costo Total de Propiedad\nCalcule: costo del equipo + instalación + mantenimiento anual + energía + agua. Divida por la vida útil esperada para obtener el costo anual real."
  },
  "misting-system-cost-breakdown": {
    title: "Desglose de Costos del Sistema de Nebulización: Bomba, Boquillas, Instalación y ROI",
    excerpt: "¿Cuánto debería costar un sistema de nebulización comercial?",
    category: "buyers-guide", date: "2026-04-05", readTime: "7 min", tags: ["precios", "ROI", "guía del comprador"],
    content: "## Comprendiendo los Costos del Sistema de Nebulización\n\n### Desglose de Costos por Componente (Sistema Comercial de 5.000 m\u00B2)\n\n**Estación de Bombeo:** $8.500 - $12.000. El componente más crítico. Las bombas VFD industriales cuestan más inicialmente pero ofrecen ahorro energético y mayor vida útil.\n\n**Boquillas (200 unidades):** $3.600 - $7.000. Las boquillas cerámicas cuestan más inicialmente pero duran 3-5 veces más que las de acero inoxidable.\n\n**Tubería y Accesorios (500 m):** $2.000 - $4.000. Se recomienda acero inoxidable 316L para instalaciones permanentes.\n\n**Sistema de Control:** $2.500 - $4.500. Los controladores IoT añaden $1.000-2.000 pero típicamente se amortizan mediante ahorros de energía/agua.\n\n**Tratamiento de Agua:** $1.500 - $3.000. Esencial para zonas de agua dura para prevenir obstrucción de boquillas.\n\n**Mano de Obra de Instalación:** $5.000 - $15.000. Varía significativamente según región y complejidad del sitio.\n\n**Costo Total del Sistema:** $23.100 - $45.500\n\n### Costos Operativos (Anuales)\n- Electricidad: $2.000 - $5.000\n- Agua: $500 - $2.000\n- Mantenimiento: $1.000 - $3.000\n- Repelente (si aplica): $500 - $2.000\n\n### Cronograma de ROI\nLa mayoría de los clientes comerciales recuperan la inversión en 8-18 meses mediante:\n- Aumento de ingresos exteriores\n- Reducción de costos de climatización\n- Extensión de temporadas operativas"
  },
};
