export const articles: Record<string, { title: string; excerpt: string; category: string; date: string; readTime: string; tags: string[]; content: string }> = {
  "how-high-pressure-misting-works": {
    title: "How High-Pressure Misting Works: The Science of Evaporative Cooling",
    excerpt: "Understand the physics behind micron-level droplet atomization.",
    category: "technical", date: "2026-05-15", readTime: "8 min", tags: ["technology", "cooling science"],
    content: "## The Physics of Evaporative Cooling\n\nWhen water transitions from liquid to vapor, it absorbs 2,257 kilojoules of thermal energy per liter — this is the latent heat of vaporization, and it's the fundamental principle behind all misting systems.\n\n### Why Pressure Matters\n\nStandard garden sprayers operate at 2-5 bar and produce droplets 100-500 microns in diameter. These large droplets have low surface-area-to-volume ratios, meaning they evaporate slowly — if at all. The result? Wet surfaces and marginal cooling.\n\nHigh-pressure misting systems operate at 70-150 bar, forcing water through precision ceramic orifices as small as 0.15mm. This creates droplets 5-15 microns in diameter — smaller than a human hair (70 microns).\n\n### The Surface Area Advantage\n\nA single liter of water atomized into 10-micron droplets creates approximately 1.9 trillion individual droplets with a combined surface area of roughly 600 m\u00B2. This enormous surface area enables near-instantaneous evaporation.\n\n### Flash Evaporation in Action\n\nWhen these micro-droplets exit the nozzle at high velocity, they encounter ambient air and begin evaporating immediately. The phase change from liquid to vapor absorbs heat directly from the surrounding air. The droplets evaporate completely within 0.5-1.5 meters from the nozzle — well before they could contact people or surfaces.\n\n### Measurable Results\n\nIn controlled testing, our systems achieve:\n- 5-8\u00B0C temperature reduction at 2 meters from nozzles\n- 8-15\u00B0C reduction in perceived temperature (accounting for wind chill)\n- 15-25% relative humidity increase (beneficial in dry climates)\n- Zero surface wetting beyond 1.5 meters\n\n### The Engineering Challenge\n\nAchieving consistent micron-level atomization requires:\n- Precision ceramic nozzles with laser-drilled orifices\n- Stable pressure delivery (VFD-controlled pumps)\n- Multi-stage water filtration to prevent clogging\n- Proper nozzle spacing and mounting height\n\nThis is why 100Cooling invests heavily in manufacturing precision — our nozzle orifice tolerance is \u00B10.005mm, verified on every unit."
  },
  "high-pressure-vs-low-pressure-misting": {
    title: "High-Pressure vs Low-Pressure Misting: A Technical Comparison",
    excerpt: "Pressure matters. A detailed technical comparison.",
    category: "technical", date: "2026-05-10", readTime: "6 min", tags: ["technology", "comparison"],
    content: "## The Pressure Spectrum\n\nMisting systems operate across a wide pressure range, from consumer-grade 7-bar units to industrial 150-bar systems. Understanding these differences is critical for B2B buyers.\n\n### Low-Pressure Systems (7-20 bar)\n- Droplet size: 50-100 microns\n- Evaporation: Partial. Surfaces get wet.\n- Cooling efficiency: 2-4\u00B0C reduction\n- Best for: Small residential patios (dry climates only)\n- Cost: $200-$800\n\n### Medium-Pressure Systems (20-50 bar)\n- Droplet size: 30-50 microns\n- Evaporation: Moderate. Some surface wetness.\n- Cooling efficiency: 3-6\u00B0C reduction\n- Best for: Small commercial patios\n- Cost: $800-$3,000\n\n### High-Pressure Systems (70-150 bar)\n- Droplet size: 5-15 microns\n- Evaporation: Complete flash evaporation\n- Cooling efficiency: 8-15\u00B0C reduction\n- Best for: Commercial, industrial, resorts\n- Cost: $8,000-$55,000\n\n### Why 100Cooling Only Builds High-Pressure\n\nThe physics is unambiguous: only high-pressure systems achieve complete evaporation. For commercial applications where guest comfort and zero wetness are non-negotiable, anything less than 70 bar is inadequate. Our 150-bar systems represent the upper end of achievable pressure for water atomization."
  },
  "outdoor-cooling-for-restaurants-guide": {
    title: "Outdoor Cooling Solutions for Restaurants: A Complete Guide",
    excerpt: "How restaurants increase outdoor seating revenue with misting.",
    category: "application", date: "2026-04-28", readTime: "10 min", tags: ["restaurants", "hospitality", "ROI"],
    content: "## The Restaurant Outdoor Dining Opportunity\n\nOutdoor seating commands 20-40% higher average check values than indoor seating. Guests linger longer, order more drinks, and return more frequently when outdoor spaces are comfortable.\n\n### The Problem\n\nIn tropical and subtropical climates, outdoor dining becomes impractical for 4-8 months of the year. Restaurants lose 30-50% of their seating capacity during peak evening hours — precisely when outdoor dining is most desirable.\n\n### The 100Cooling Solution\n\nCeiling-mounted or pergola-integrated misting lines create an invisible cooling envelope over dining areas. Key installation considerations:\n\n**Nozzle Placement:** Mounted 2.5-3.5 meters high, spaced 0.8-1.2 meters apart along the perimeter.\n\n**Zone Control:** Divide the space into independently controlled zones (bar area, main dining, private sections).\n\n**Evening Mosquito Control:** The same system delivers timed repellent misting during peak mosquito hours (5PM-9PM).\n\n### Real ROI Data\n\nOur restaurant clients report:\n- 30-60% increase in outdoor seating revenue\n- Extension of outdoor dining season by 3-6 months\n- 22% increase in average dwell time\n- ROI achieved in 6-12 months\n\n### Case Example\n\nA 120-seat beachfront restaurant in Phuket installed 100Cooling across their terrace. Before: terrace closed June-September, open but underutilized October-May. After: terrace fully operational year-round, revenue up 40%, became the most-booked section of the restaurant."
  },
  "factory-floor-cooling-productivity": {
    title: "Factory Floor Cooling: Reducing Heat Stress & Improving Productivity",
    excerpt: "How industrial misting delivers measurable productivity gains.",
    category: "application", date: "2026-04-20", readTime: "7 min", tags: ["industrial", "productivity", "ROI"],
    content: "## The Hidden Cost of Heat in Manufacturing\n\nFactory floors in tropical regions routinely exceed 35-40\u00B0C. Research shows:\n- Worker productivity drops 2% per degree above 26\u00B0C\n- Accident rates increase 6% per degree above 30\u00B0C\n- Absenteeism rises 15-25% during heat waves\n\n### Why Traditional Cooling Fails\n\nAir conditioning a 15,000 m\u00B2 factory with 12-meter ceilings is economically impossible. Energy costs would exceed $50,000/month. Spot cooling with fans provides zero temperature reduction.\n\n### The 100Cooling Industrial Approach\n\nTargeted misting lines above worker stations create micro-climate zones. Workers experience 26-28\u00B0C while the ambient factory temperature remains 35\u00B0C+. Energy cost: approximately $200/month for a 5,000 m\u00B2 installation.\n\n### Measurable Results\n\nTechTronics Manufacturing, Shenzhen (15,000 m\u00B2):\n- Floor temperature: 38\u00B0C \u2192 26\u00B0C (measured at worker stations)\n- Productivity: +22%\n- Defect rate: -18%\n- Absenteeism: -31%\n- ROI: 8 months\n\n### Dust Suppression Bonus\n\nIndustrial misting also suppresses airborne dust particles. In wood processing, textile, and mining facilities, this provides additional compliance and worker health benefits."
  },
  "how-to-choose-misting-system": {
    title: "How to Choose the Right Outdoor Cooling System",
    excerpt: "A comprehensive buyer's checklist for evaluating proposals.",
    category: "buyers-guide", date: "2026-04-12", readTime: "9 min", tags: ["buyers guide", "evaluation"],
    content: "## The 10-Point Misting System Evaluation Checklist\n\n### 1. Operating Pressure\nAsk for the actual pump pressure rating, not marketing claims. Industrial systems should specify 70-150 bar. Be wary of systems claiming \"high pressure\" below 50 bar.\n\n### 2. Nozzle Specifications\nRequest orifice size (should be 0.15mm or smaller), material (ceramic > stainless steel), and anti-drip mechanism.\n\n### 3. Pump Construction\n316L stainless steel pump head is the industry standard. Brass or aluminum components indicate consumer-grade equipment.\n\n### 4. Filtration Stages\nA minimum 3-stage filtration is essential. 5-stage is recommended for commercial. 10-stage for industrial or hard water.\n\n### 5. Control System\nLook for zone-level control, weather-based scheduling, remote monitoring capability, and data logging.\n\n### 6. Tubing Material\n316L stainless steel for permanent installations. Nylon acceptable for temporary/rental applications.\n\n### 7. Warranty Terms\nIndustry-standard: 3-5 years on pump, 2-3 years on nozzles. Extended warranties indicate manufacturer confidence.\n\n### 8. Certifications\nVerify ISO 9001, CE marking, RoHS compliance. UL listing required for North American markets.\n\n### 9. Installation Support\nDoes the manufacturer provide installation supervision? Are there certified partners in your region?\n\n### 10. Total Cost of Ownership\nCalculate: equipment cost + installation + annual maintenance + energy + water. Divide by expected lifespan for true annual cost."
  },
  "misting-system-cost-breakdown": {
    title: "Misting System Cost Breakdown: Pump, Nozzles, Installation & ROI",
    excerpt: "What should a commercial misting system cost?",
    category: "buyers-guide", date: "2026-04-05", readTime: "7 min", tags: ["pricing", "ROI", "buyers guide"],
    content: "## Understanding Misting System Costs\n\n### Component Cost Breakdown (5,000 m\u00B2 Commercial System)\n\n**Pump Station:** $8,500 - $12,000. The most critical component. Industrial VFD pumps cost more but deliver energy savings and longer lifespan.\n\n**Nozzles (200 units):** $3,600 - $7,000. Ceramic nozzles cost more initially but last 3-5x longer than stainless steel.\n\n**Tubing & Fittings (500m):** $2,000 - $4,000. 316L stainless steel recommended for permanent installations.\n\n**Control System:** $2,500 - $4,500. IoT controllers add $1,000-2,000 but typically pay back through energy/water savings.\n\n**Water Treatment:** $1,500 - $3,000. Essential for hard water areas to prevent nozzle clogging.\n\n**Installation Labor:** $5,000 - $15,000. Varies significantly by region and site complexity.\n\n**Total System Cost:** $23,100 - $45,500\n\n### Operating Costs (Annual)\n- Electricity: $2,000 - $5,000\n- Water: $500 - $2,000\n- Maintenance: $1,000 - $3,000\n- Repellent (if applicable): $500 - $2,000\n\n### ROI Timeline\nMost commercial clients recover investment in 8-18 months through:\n- Increased outdoor revenue\n- Reduced HVAC costs\n- Extended operating seasons"
  },
};
