export const articles: Record<string, { title: string; excerpt: string; category: string; date: string; readTime: string; tags: string[]; content: string }> = {
  "how-high-pressure-misting-works": {
    title: "Comment Fonctionne la Brumisation Haute Pression : La Science du Refroidissement Évaporatif",
    excerpt: "Comprenez la physique derrière l'atomisation des gouttelettes au niveau micronique.",
    category: "technical", date: "2026-05-15", readTime: "8 min", tags: ["technologie", "science du refroidissement"],
    content: "## La Physique du Refroidissement Évaporatif\n\nLorsque l'eau passe de l'état liquide à l'état vapeur, elle absorbe 2 257 kilojoules d'énergie thermique par litre — c'est la chaleur latente de vaporisation, et c'est le principe fondamental derrière tous les systèmes de brumisation.\n\n### Pourquoi la Pression est Importante\n\nLes pulvérisateurs de jardin standard fonctionnent à 2-5 bars et produisent des gouttelettes de 100-500 microns de diamètre. Ces grosses gouttelettes ont un faible rapport surface-volume, ce qui signifie qu'elles s'évaporent lentement — voire pas du tout. Le résultat ? Des surfaces mouillées et un refroidissement marginal.\n\nLes systèmes de brumisation haute pression fonctionnent à 70-150 bars, forçant l'eau à travers des orifices céramiques de précision aussi petits que 0,15 mm. Cela crée des gouttelettes de 5-15 microns de diamètre — plus petites qu'un cheveu humain (70 microns).\n\n### L'Avantage de la Surface\n\nUn seul litre d'eau atomisé en gouttelettes de 10 microns crée environ 1,9 billion de gouttelettes individuelles avec une surface combinée d'environ 600 m\u00B2. Cette surface énorme permet une évaporation quasi instantanée.\n\n### L'Évaporation Instantanée en Action\n\nLorsque ces micro-gouttelettes sortent de la buse à haute vitesse, elles rencontrent l'air ambiant et commencent à s'évaporer immédiatement. Le changement de phase de liquide à vapeur absorbe la chaleur directement de l'air environnant. Les gouttelettes s'évaporent complètement dans les 0,5-1,5 mètres de la buse — bien avant de pouvoir entrer en contact avec les personnes ou les surfaces.\n\n### Résultats Mesurables\n\nLors de tests contrôlés, nos systèmes atteignent :\n- Une réduction de température de 5-8\u00B0C à 2 mètres des buses\n- Une réduction de 8-15\u00B0C de la température ressentie (en tenant compte du refroidissement éolien)\n- Une augmentation de l'humidité relative de 15-25% (bénéfique en climats secs)\n- Zéro mouillage de surface au-delà de 1,5 mètre\n\n### Le Défi d'Ingénierie\n\nAtteindre une atomisation constante au niveau micronique nécessite :\n- Des buses céramiques de précision avec orifices percés au laser\n- Une distribution de pression stable (pompes contrôlées par VFD)\n- Une filtration d'eau multi-étapes pour prévenir l'obstruction\n- Un espacement approprié des buses et une hauteur de montage optimale pour la couverture de brume"
  },
  "high-pressure-vs-low-pressure-misting": {
    title: "Brumisation Haute Pression vs Basse Pression : Une Comparaison Technique",
    excerpt: "La pression compte. Une comparaison technique détaillée.",
    category: "technical", date: "2026-05-10", readTime: "6 min", tags: ["technologie", "comparaison"],
    content: "## Le Spectre de Pression\n\nLes systèmes de brumisation fonctionnent sur une large plage de pression, des unités grand public de 7 bars aux systèmes industriels de 150 bars. Comprendre ces différences est essentiel pour les acheteurs B2B.\n\n### Systèmes Basse Pression (7-20 bars)\n- Taille des gouttelettes : 50-100 microns\n- Évaporation : Partielle. Les surfaces sont mouillées.\n- Efficacité de refroidissement : Réduction de 2-4\u00B0C\n- Idéal pour : Petites terrasses résidentielles (climats secs uniquement)\n- Coût : 200-800 $\n\n### Systèmes Moyenne Pression (20-50 bars)\n- Taille des gouttelettes : 30-50 microns\n- Évaporation : Modérée. Légère humidité de surface.\n- Efficacité de refroidissement : Réduction de 3-6\u00B0C\n- Idéal pour : Petites terrasses commerciales\n- Coût : 800-3 000 $\n\n### Systèmes Haute Pression (70-150 bars)\n- Taille des gouttelettes : 5-15 microns\n- Évaporation : Évaporation instantanée complète\n- Efficacité de refroidissement : Réduction de 8-15\u00B0C\n- Idéal pour : Commercial, industriel, resorts\n- Coût : 8 000-55 000 $\n\n### Pourquoi 100Cooling Ne Construit Que de la Haute Pression\n\nLa physique est sans équivoque : seuls les systèmes haute pression atteignent une évaporation complète. Pour les applications commerciales où le confort des clients et l'absence totale d'humidité sont non négociables, tout niveau inférieur à 70 bars est inadéquat. Nos systèmes 150 bars représentent la limite supérieure de pression atteignable pour l'atomisation de l'eau."
  },
  "outdoor-cooling-for-restaurants-guide": {
    title: "Solutions de Refroidissement Extérieur pour Restaurants : Un Guide Complet",
    excerpt: "Comment les restaurants augmentent les revenus des terrasses avec la brumisation.",
    category: "application", date: "2026-04-28", readTime: "10 min", tags: ["restaurants", "hôtellerie", "ROI"],
    content: "## L'Opportunité de la Restauration en Extérieur\n\nLes places en terrasse génèrent des tickets moyens 20-40% plus élevés que les places en intérieur. Les clients restent plus longtemps, commandent plus de boissons et reviennent plus fréquemment lorsque les espaces extérieurs sont confortables.\n\n### Le Problème\n\nDans les climats tropicaux et subtropicaux, la restauration en extérieur devient impraticable pendant 4-8 mois par an. Les restaurants perdent 30-50% de leur capacité d'accueil pendant les heures de pointe du soir — précisément lorsque la restauration en extérieur est la plus recherchée.\n\n### La Solution 100Cooling\n\nDes lignes de brumisation montées au plafond ou intégrées aux pergolas créent une enveloppe de refroidissement invisible au-dessus des zones de restauration. Considérations clés d'installation :\n\n**Positionnement des Buses :** Montées à 2,5-3,5 mètres de hauteur, espacées de 0,8-1,2 mètre le long du périmètre.\n\n**Contrôle par Zones :** Divisez l'espace en zones contrôlées indépendamment (zone bar, salle principale, sections privées).\n\n**Contrôle des Moustiques en Soirée :** Le même système délivre une brumisation répulsive programmée pendant les heures de pointe des moustiques (17h-21h).\n\n### Données Réelles de ROI\n\nNos clients restaurateurs rapportent :\n- Augmentation de 30-60% des revenus de terrasse\n- Extension de la saison de restauration extérieure de 3-6 mois\n- Augmentation de 22% du temps moyen de présence\n- ROI atteint en 6-12 mois\n\n### Exemple de Cas\n\nUn restaurant de plage de 120 couverts à Phuket a installé 100Cooling sur toute sa terrasse. Avant : terrasse fermée juin-septembre, ouverte mais sous-utilisée octobre-mai. Après : terrasse pleinement opérationnelle toute l'année, revenus en hausse de 40%, devenue la section la plus réservée du restaurant."
  },
  "factory-floor-cooling-productivity": {
    title: "Refroidissement des Ateliers d'Usine : Réduire le Stress Thermique et Améliorer la Productivité",
    excerpt: "Comment la brumisation industrielle offre des gains de productivité mesurables.",
    category: "application", date: "2026-04-20", readTime: "7 min", tags: ["industriel", "productivité", "ROI"],
    content: "## Le Coût Caché de la Chaleur dans l'Industrie Manufacturière\n\nLes ateliers d'usine en régions tropicales dépassent régulièrement 35-40\u00B0C. Les recherches montrent :\n- La productivité des travailleurs chute de 2% par degré au-dessus de 26\u00B0C\n- Les taux d'accidents augmentent de 6% par degré au-dessus de 30\u00B0C\n- L'absentéisme augmente de 15-25% pendant les vagues de chaleur\n\n### Pourquoi le Refroidissement Traditionnel Échoue\n\nClimatiser une usine de 15 000 m\u00B2 avec des plafonds de 12 mètres est économiquement impossible. Les coûts énergétiques dépasseraient 50 000 $/mois. Le refroidissement ponctuel par ventilateurs n'apporte aucune réduction de température.\n\n### L'Approche Industrielle 100Cooling\n\nDes lignes de brumisation ciblées au-dessus des postes de travail créent des zones de microclimat. Les travailleurs ressentent 26-28\u00B0C tandis que la température ambiante de l'usine reste à 35\u00B0C+. Coût énergétique : environ 200 $/mois pour une installation de 5 000 m\u00B2.\n\n### Résultats Mesurables\n\nTechTronics Manufacturing, Shenzhen (15 000 m\u00B2) :\n- Température au sol : 38\u00B0C → 26\u00B0C (mesurée aux postes de travail)\n- Productivité : +22%\n- Taux de défauts : -18%\n- Absentéisme : -31%\n- ROI : 8 mois\n\n### Avantage Supplémentaire : Suppression des Poussières\n\nLa brumisation industrielle supprime également les particules de poussière en suspension. Dans les installations de transformation du bois, du textile et les sites miniers, cela apporte des avantages supplémentaires en matière de conformité et de santé des travailleurs."
  },
  "how-to-choose-misting-system": {
    title: "Comment Choisir le Bon Système de Refroidissement Extérieur",
    excerpt: "Une liste de contrôle complète pour l'acheteur afin d'évaluer les propositions.",
    category: "buyers-guide", date: "2026-04-12", readTime: "9 min", tags: ["guide d'achat", "évaluation"],
    content: "## La Liste de Contrôle en 10 Points pour l'Évaluation d'un Système de Brumisation\n\n### 1. Pression de Fonctionnement\nDemandez la pression nominale réelle de la pompe, pas les affirmations marketing. Les systèmes industriels doivent spécifier 70-150 bars. Méfiez-vous des systèmes prétendant « haute pression » en dessous de 50 bars.\n\n### 2. Spécifications des Buses\nDemandez la taille d'orifice (doit être de 0,15 mm ou moins), le matériau (céramique > acier inoxydable) et le mécanisme anti-goutte.\n\n### 3. Construction de la Pompe\nUne tête de pompe en acier inoxydable 316L est la norme industrielle. Les composants en laiton ou aluminium indiquent un équipement de qualité grand public.\n\n### 4. Étages de Filtration\nUn minimum de 3 étages de filtration est essentiel. 5 étages recommandés pour le commercial. 10 étages pour l'industriel ou l'eau dure.\n\n### 5. Système de Contrôle\nRecherchez un contrôle au niveau des zones, une programmation basée sur la météo, une capacité de surveillance à distance et un enregistrement des données.\n\n### 6. Matériau des Tuyaux\nAcier inoxydable 316L pour les installations permanentes. Nylon acceptable pour les applications temporaires/de location.\n\n### 7. Conditions de Garantie\nNorme industrielle : 3-5 ans sur la pompe, 2-3 ans sur les buses. Les garanties prolongées indiquent la confiance du fabricant.\n\n### 8. Certifications\nVérifiez ISO 9001, marquage CE, conformité RoHS. Certification UL requise pour les marchés nord-américains.\n\n### 9. Support d'Installation\nLe fabricant fournit-il une supervision d'installation ? Y a-t-il des partenaires certifiés dans votre région ?\n\n### 10. Coût Total de Possession\nCalculez : coût de l'équipement + installation + maintenance annuelle + énergie + eau. Divisez par la durée de vie prévue pour obtenir le coût annuel réel."
  },
  "misting-system-cost-breakdown": {
    title: "Décomposition des Coûts du Système de Brumisation : Pompe, Buses, Installation et ROI",
    excerpt: "Combien devrait coûter un système de brumisation commercial ?",
    category: "buyers-guide", date: "2026-04-05", readTime: "7 min", tags: ["tarification", "ROI", "guide d'achat"],
    content: "## Comprendre les Coûts du Système de Brumisation\n\n### Décomposition des Coûts par Composant (Système Commercial de 5 000 m\u00B2)\n\n**Station de Pompage :** 8 500 - 12 000 $. Le composant le plus critique. Les pompes VFD industrielles coûtent plus cher au départ mais offrent des économies d'énergie et une durée de vie plus longue.\n\n**Buses (200 unités) :** 3 600 - 7 000 $. Les buses céramiques coûtent plus cher initialement mais durent 3 à 5 fois plus longtemps que l'acier inoxydable.\n\n**Tuyauterie et Raccords (500 m) :** 2 000 - 4 000 $. Acier inoxydable 316L recommandé pour les installations permanentes.\n\n**Système de Contrôle :** 2 500 - 4 500 $. Les contrôleurs IoT ajoutent 1 000-2 000 $ mais sont généralement amortis par les économies d'énergie/d'eau.\n\n**Traitement de l'Eau :** 1 500 - 3 000 $. Essentiel pour les zones à eau dure pour prévenir l'obstruction des buses.\n\n**Main-d'Œuvre d'Installation :** 5 000 - 15 000 $. Varie considérablement selon la région et la complexité du site.\n\n**Coût Total du Système :** 23 100 - 45 500 $\n\n### Coûts d'Exploitation (Annuel)\n- Électricité : 2 000 - 5 000 $\n- Eau : 500 - 2 000 $\n- Maintenance : 1 000 - 3 000 $\n- Répulsif (le cas échéant) : 500 - 2 000 $\n\n### Calendrier de ROI\nLa plupart des clients commerciaux récupèrent leur investissement en 8-18 mois grâce à :\n- L'augmentation des revenus extérieurs\n- La réduction des coûts de climatisation\n- L'extension des saisons d'exploitation"
  },
};
